In [1]:
import pandas as pd

In [2]:
houses = pd.read_csv(f"C:/Users/GODIAH/Downloads/houserecommender/synthetic_house_recommendation_data (1).csv")

In [3]:
houses

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're..."
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf..."
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil..."
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l..."
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma..."
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli..."
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f..."
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l..."
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ..."
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra..."

In [4]:
houses["words_in_house_keywords"] = houses["house_keywords"].str.split().str.len()
houses

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655

In [5]:
houses.loc[houses["words_in_house_keywords"].between(1,20),"house_keywords"]

83       ['beach-house', 'eco-friendly', 'studio', 'shu...
125      ['heated-floors', 'energy-star', 'roof-deck', ...
141                                          ['renovated']
155      ['sunny', 'wall-sconces', 'backup-generator', ...
172      ['heated-floors', 'safe', 'newly-built', 'deck...
                               ...
29692    ['dishwasher', 'asbestos-free', 'carpeted', 'q...
29806    ['seasonal-living', 'centrally-located', 'sust...
29820    ['grand-entrance', 'ocean-view', 'French-doors...
29870    ['hardwood-cabinets', 'eco-conscious', 'suburb...
29915    ['well-maintained', 'private', 'drought-tolera...
Name: house_keywords, Length: 632, dtype: object

In [6]:
house_data = houses[houses["words_in_house_keywords"] >= 25]
house_data

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655

In [9]:
# Create a copy
house_data = house_data.copy()

In [10]:
# Remove duplicate house keywords
import ast

def remove_duplicates(keyword_list):
    """
    Remove duplicate keywords from a list while preserving the original order.
    """
    return list(dict.fromkeys(keyword_list))

house_data.loc[:, 'house_keywords'] = house_data['house_keywords'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

house_data.loc[:, 'house_keywords'] = house_data['house_keywords'].apply(remove_duplicates)

In [11]:
house_data['house_keywords'] = house_data['house_keywords'].apply(str)
house_data["new_words_in_keywords"] = house_data["house_keywords"].str.split().str.len()
house_data

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957,286
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233,160
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134,109
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250,172
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621,255
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513,250
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475,243
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598,264
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655,265

In [12]:
duplicate_coordinates = house_data[house_data.duplicated(subset=["latitude", "longitude"], keep=False)]

if len(duplicate_coordinates) > 0:
    print(f"Found {len(duplicate_coordinates)} records with duplicate coordinates:")
    print(duplicate_coordinates)
else:
    print("No duplicate coordinates found in the dataset.")

Found 4127 records with duplicate coordinates:
       Unnamed: 0   latitude  longitude     house_type      price  bedrooms  \
7               7  51.633250   0.008156       Terraced  194116.44         3
13             13  51.445922  -2.583433       Bungalow  142819.47         2
31             31  53.541494  -2.099826       Terraced  225315.47         1
37             37  53.721740  -2.464049  Semi-Detached  489860.16         4
48             48  53.784935  -1.067699           Flat  765105.60         3
...           ...        ...        ...            ...        ...       ...
29969       29969  50.255270  -5.046154  Semi-Detached  352483.27         3
29972       29972  55.793568  -3.994933       Terraced   83603.56         3
29977       29977         \N         \N           Flat  596257.82         2
29979       29979  50.725914  -3.464073           Flat  290186.88         1
29993       29993         \N         \N           Flat  180961.09         4

       bathrooms neighbourhood_quality house_condition crime_rate  \
7              1           Outstanding         Alright        Low
13             3               Alright        Pleasant        Low
31             1              Pleasant         Abysmal   Very Low
37             1              Pleasant         Alright       High
48             3           Outstanding         Alright  Very High
...          ...                   ...             ...        ...
29969          3           Outstanding         Alright     Medium
29972          2               Alright         Alright     Medium
29977          1                 Rough        Pleasant     Medium
29979          2               Alright         Alright     Medium
29993          1              Pleasant           Rough        Low

       garden_size                                     house_keywords  \
7           110.41  ['pantry', 'secondhand', 'reverse-osmosis', 'g...
13          106.44  ['native-landscaping', 'asbestos-free', 'balco...
31          156.70  ['airy', 'organic-gardening', 'exposed-beams',...
37          537.28  ['airy', 'front-yard', 'tile-backsplash', 'bir...
48           16.56  ['garden', 'double-oven', 'game-room', 'unfurn...
...            ...                                                ...
29969        21.85  ['shutters', 'senior-friendly', 'dog-run', 'to...
29972       407.91  ['chateau', 'breathtaking', 'pantry', 'jacuzzi...
29977       123.68  ['emergency-exit', 'accessible', 'mold-inspect...
29979        37.92  ['library', 'reception', 'workshop', 'thermal-...
29993         2.69  ['lake-house', 'apartment', 'vintage-style', '...

       words_in_house_keywords  new_words_in_keywords
7                          781                    284
13                         407                    236
31                          56                     48
37                         957                    291
48                         813                    282
...                        ...                    ...
29969                      425                    232
29972                      337                    202
29977                      186                    140
29979                      629                    260
29993                       29                     28

[4127 rows x 14 columns]

In [14]:
house_data_no_duplicates = house_data.drop_duplicates(subset=["latitude", "longitude"], keep='first')

records_removed = len(house_data) - len(house_data_no_duplicates)
print(f"\nRemoved {records_removed} duplicate coordinate records.")
print(f"Original dataset size: {len(house_data)}")
print(f"New dataset size: {len(house_data_no_duplicates)}")

Removed 2979 duplicate coordinate records.
Original dataset size: 29242
New dataset size: 26263

In [15]:
house_data_no_duplicates

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957,286
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233,160
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134,109
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250,172
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621,255
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513,250
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475,243
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598,264
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655,265

In [18]:
# Combine latitude and longitude
house_data_no_duplicates = house_data.drop_duplicates(subset=["latitude", "longitude"], keep='first').copy()
house_data_no_duplicates["co-ordinates"] = house_data_no_duplicates[["latitude","longitude"]].astype(str).agg(" ".join,axis=1)
house_data_no_duplicates

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords,co-ordinates
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957,286,53.108470 -0.411203
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233,160,55.854867 -4.279985
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134,109,51.523723 -2.500452
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250,172,51.759018 -0.245954
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943,286,50.731135 -3.504734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621,255,54.145806 -1.098392
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513,250,51.453650 -2.454582
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475,243,51.450533 0.077056
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598,264,52.292070 -0.839813
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655,265,51.109482 -0.232709

In [19]:
# Create a unique identifier for each house
house_data_no_duplicates["tag"] = range(1, len(house_data_no_duplicates) + 1)
house_data_no_duplicates

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords,co-ordinates,tag
0,0,53.108470,-0.411203,Terraced,300890.76,7,4,Pleasant,Abysmal,High,94.20,"['reception', 'forest-view', 'study-room', 're...",957,286,53.108470 -0.411203,1
1,1,55.854867,-4.279985,Land,272455.06,4,3,Pleasant,Alright,Medium,260.42,"['garden', 'laundry-room', 'comfortable', 'saf...",233,160,55.854867 -4.279985,2
2,2,51.523723,-2.500452,Land,172964.52,1,3,Pleasant,Alright,Medium,78.91,"['sauna', 'secure', 'recessed-lighting', 'buil...",134,109,51.523723 -2.500452,3
3,3,51.759018,-0.245954,Terraced,329183.39,3,1,Alright,Pleasant,Medium,31.37,"['crown-molding', 'greenhouse', 'peaceful', 'l...",250,172,51.759018 -0.245954,4
4,4,50.731135,-3.504734,Terraced,739525.34,3,2,Pleasant,Alright,Low,6.00,"['convenient', 'condo', 'water-saving', 'perma...",943,286,50.731135 -3.504734,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,54.145806,-1.098392,Terraced,182299.41,4,1,Abysmal,Pleasant,Low,113.02,"['stylish', 'breathtaking', 'peaceful', 'polli...",621,255,54.145806 -1.098392,26259
29996,29996,51.453650,-2.454582,Flat,382311.13,6,3,Alright,Abysmal,Low,25.76,"['pond', 'historic', 'water-softener', 'lead-f...",513,250,51.453650 -2.454582,26260
29997,29997,51.450533,0.077056,Flat,711553.90,3,2,Rough,Alright,Low,125.45,"['historic', 'native-plants', 'gym', 'native-l...",475,243,51.450533 0.077056,26261
29998,29998,52.292070,-0.839813,Terraced,661023.67,3,3,Rough,Alright,Very Low,16.34,"['heated-floors', 'arched-doorways', 'gated', ...",598,264,52.292070 -0.839813,26262
29999,29999,51.109482,-0.232709,Flat,336810.39,1,4,Pleasant,Pleasant,Very High,331.61,"['energy-star', 'garden', 'dishwasher', 'libra...",655,265,51.109482 -0.232709,26263

In [24]:
# Count records with less than 100 house keywords
count_less_than_100 = house_data_no_duplicates[house_data_no_duplicates["new_words_in_keywords"] < 100].shape[0]
print("Records with less than 100 keywords:", count_less_than_100)

Records with less than 100 keywords: 2586

In [25]:
# Drop Records with more than 100 house keywords
houses_filtered = house_data_no_duplicates[house_data_no_duplicates["new_words_in_keywords"] <= 100]

# Optionally, check the shape of the filtered DataFrame
print("Records after dropping those with >100 keywords:", houses_filtered.shape[0])

Records after dropping those with >100 keywords: 2621

In [27]:
# Reset the tag index
houses_filtered = houses_filtered.reset_index(drop=True)

# Create a new "tag" column that auto-increments from 1
houses_filtered["tag"] = houses_filtered.index + 1
houses_filtered

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords,co-ordinates,tag
0,20,50.846545,-0.539285,Semi-Detached,1032367.15,3,3,Pleasant,Alright,High,19.67,"['chateau', 'non-toxic-materials', 'secluded',...",77,69,50.846545 -0.539285,1
1,28,50.894080,-2.750017,Flat,462379.82,3,1,Rough,Alright,Medium,951.33,"['basement', 'workshop', 'art-studio', 'scenic...",36,35,50.894080 -2.750017,2
2,31,53.541494,-2.099826,Terraced,225315.47,1,1,Pleasant,Abysmal,Very Low,156.70,"['airy', 'organic-gardening', 'exposed-beams',...",56,48,53.541494 -2.099826,3
3,54,51.414573,-0.370068,Terraced,763644.90,5,2,Pleasant,Alright,Low,6.49,"['community-garden', 'ecosystem-friendly', 'ap...",109,94,51.414573 -0.370068,4
4,62,54.900993,-1.393848,Bungalow,79402.78,6,1,Pleasant,Alright,Medium,253.48,"['dog-run', 'municipal-water', 'radon-mitigati...",30,28,54.900993 -1.393848,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2616,29948,57.184340,-2.181028,Terraced,370515.03,3,2,Pleasant,Alright,Medium,52.57,"['courtyard', 'flood-resistant', 'workshop', '...",63,57,57.184340 -2.181028,2617
2617,29974,53.899039,-1.738359,Terraced,685726.47,3,2,Pleasant,Pleasant,Very High,9.18,"['carpeted', 'stone-wall', 'ample-storage', 'f...",73,64,53.899039 -1.738359,2618
2618,29976,51.491219,0.163004,Terraced,106448.44,6,4,Outstanding,Alright,Medium,21.51,"['vegetable-garden', 'outdoor-kitchen', 'rural...",63,53,51.491219 0.163004,2619
2619,29984,51.322855,-0.547465,Flat,200903.87,5,1,Alright,Alright,Medium,6.33,"['comfortable', 'partly-furnished', 'villa', '...",119,88,51.322855 -0.547465,2620
2620,29987,51.803890,0.346973,Park Home,72283.36,2,1,Outstanding,Pleasant,Medium,9.75,"['barbecue-area', 'butler-pantry', 'zero-waste...",119,93,51.803890 0.346973,2621

In [29]:
# Create new unique identifier
houses_filtered["house_tag"] = houses_filtered[["tag", "house_keywords"]].astype(str).agg(" ".join, axis=1)
houses_filtered

,Unnamed: 0,latitude,longitude,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,words_in_house_keywords,new_words_in_keywords,co-ordinates,tag,house_tag
0,20,50.846545,-0.539285,Semi-Detached,1032367.15,3,3,Pleasant,Alright,High,19.67,"['chateau', 'non-toxic-materials', 'secluded',...",77,69,50.846545 -0.539285,1,"1 ['chateau', 'non-toxic-materials', 'secluded..."
1,28,50.894080,-2.750017,Flat,462379.82,3,1,Rough,Alright,Medium,951.33,"['basement', 'workshop', 'art-studio', 'scenic...",36,35,50.894080 -2.750017,2,"2 ['basement', 'workshop', 'art-studio', 'scen..."
2,31,53.541494,-2.099826,Terraced,225315.47,1,1,Pleasant,Abysmal,Very Low,156.70,"['airy', 'organic-gardening', 'exposed-beams',...",56,48,53.541494 -2.099826,3,"3 ['airy', 'organic-gardening', 'exposed-beams..."
3,54,51.414573,-0.370068,Terraced,763644.90,5,2,Pleasant,Alright,Low,6.49,"['community-garden', 'ecosystem-friendly', 'ap...",109,94,51.414573 -0.370068,4,"4 ['community-garden', 'ecosystem-friendly', '..."
4,62,54.900993,-1.393848,Bungalow,79402.78,6,1,Pleasant,Alright,Medium,253.48,"['dog-run', 'municipal-water', 'radon-mitigati...",30,28,54.900993 -1.393848,5,"5 ['dog-run', 'municipal-water', 'radon-mitiga..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2616,29948,57.184340,-2.181028,Terraced,370515.03,3,2,Pleasant,Alright,Medium,52.57,"['courtyard', 'flood-resistant', 'workshop', '...",63,57,57.184340 -2.181028,2617,"2617 ['courtyard', 'flood-resistant', 'worksho..."
2617,29974,53.899039,-1.738359,Terraced,685726.47,3,2,Pleasant,Pleasant,Very High,9.18,"['carpeted', 'stone-wall', 'ample-storage', 'f...",73,64,53.899039 -1.738359,2618,"2618 ['carpeted', 'stone-wall', 'ample-storage..."
2618,29976,51.491219,0.163004,Terraced,106448.44,6,4,Outstanding,Alright,Medium,21.51,"['vegetable-garden', 'outdoor-kitchen', 'rural...",63,53,51.491219 0.163004,2619,"2619 ['vegetable-garden', 'outdoor-kitchen', '..."
2619,29984,51.322855,-0.547465,Flat,200903.87,5,1,Alright,Alright,Medium,6.33,"['comfortable', 'partly-furnished', 'villa', '...",119,88,51.322855 -0.547465,2620,"2620 ['comfortable', 'partly-furnished', 'vill..."
2620,29987,51.803890,0.346973,Park Home,72283.36,2,1,Outstanding,Pleasant,Medium,9.75,"['barbecue-area', 'butler-pantry', 'zero-waste...",119,93,51.803890 0.346973,2621,"2621 ['barbecue-area', 'butler-pantry', 'zero-..."

In [31]:
{
    houses_filtered
    .drop(["Unnamed: 0","latitude","longitude","words_in_house_keywords"],axis=1)
    .to_csv("house_data_cleaned_v2.csv", index = False)
}

{None}

In [32]:
houses_cleaned = pd.read_csv('house_data_cleaned_v2.csv')
houses_cleaned

,house_type,price,bedrooms,bathrooms,neighbourhood_quality,house_condition,crime_rate,garden_size,house_keywords,new_words_in_keywords,co-ordinates,tag,house_tag
0,Semi-Detached,1032367.15,3,3,Pleasant,Alright,High,19.67,"['chateau', 'non-toxic-materials', 'secluded',...",69,50.846545 -0.539285,1,"1 ['chateau', 'non-toxic-materials', 'secluded..."
1,Flat,462379.82,3,1,Rough,Alright,Medium,951.33,"['basement', 'workshop', 'art-studio', 'scenic...",35,50.894080 -2.750017,2,"2 ['basement', 'workshop', 'art-studio', 'scen..."
2,Terraced,225315.47,1,1,Pleasant,Abysmal,Very Low,156.70,"['airy', 'organic-gardening', 'exposed-beams',...",48,53.541494 -2.099826,3,"3 ['airy', 'organic-gardening', 'exposed-beams..."
3,Terraced,763644.90,5,2,Pleasant,Alright,Low,6.49,"['community-garden', 'ecosystem-friendly', 'ap...",94,51.414573 -0.370068,4,"4 ['community-garden', 'ecosystem-friendly', '..."
4,Bungalow,79402.78,6,1,Pleasant,Alright,Medium,253.48,"['dog-run', 'municipal-water', 'radon-mitigati...",28,54.900993 -1.393848,5,"5 ['dog-run', 'municipal-water', 'radon-mitiga..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2616,Terraced,370515.03,3,2,Pleasant,Alright,Medium,52.57,"['courtyard', 'flood-resistant', 'workshop', '...",57,57.184340 -2.181028,2617,"2617 ['courtyard', 'flood-resistant', 'worksho..."
2617,Terraced,685726.47,3,2,Pleasant,Pleasant,Very High,9.18,"['carpeted', 'stone-wall', 'ample-storage', 'f...",64,53.899039 -1.738359,2618,"2618 ['carpeted', 'stone-wall', 'ample-storage..."
2618,Terraced,106448.44,6,4,Outstanding,Alright,Medium,21.51,"['vegetable-garden', 'outdoor-kitchen', 'rural...",53,51.491219 0.163004,2619,"2619 ['vegetable-garden', 'outdoor-kitchen', '..."
2619,Flat,200903.87,5,1,Alright,Alright,Medium,6.33,"['comfortable', 'partly-furnished', 'villa', '...",88,51.322855 -0.547465,2620,"2620 ['comfortable', 'partly-furnished', 'vill..."
2620,Park Home,72283.36,2,1,Outstanding,Pleasant,Medium,9.75,"['barbecue-area', 'butler-pantry', 'zero-waste...",93,51.803890 0.346973,2621,"2621 ['barbecue-area', 'butler-pantry', 'zero-..."